### ISSUE TITLE
New sodium version doesnt work with nvidium [includes temp solution]

### ISSUE THREAD

**Issue by CristianP09** [MCRcortex/nvidium#204]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
Hemos encontrado una solución prometedora:
	 - Cambia el mod 'Nvidium' (nvidium) 0.2.6-beta por cualquier versión que sea compatible con:
		 - sodium 0.5.10+mc1.20.1
Dependencias no satisfechas:
	 - ¡El mod 'Nvidium' (nvidium) 0.2.6-beta necesita la versión 0.5.7 o la versión 0.5.8 de el mod 'Sodium' (sodium), pero sólo tienes una versión incorrecta: 0.5.10+mc1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

I have changed the mods as advised and it gives me more errors with iris for example. I don't know what to do because I really don't understand the error.

**Comment by MrCatlio** [comment]
use sodium 0.5.8 or 0.5.7 since the mod has not being updated for 1.20.1 use the latest version of sodium

**Comment by CristianP09** [comment]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
Hemos encontrado una solución prometedora:
	 - Quita el mod 'Nvidium' (nvidium) 0.2.6-beta (C:\Users\rosad\AppData\Roaming\com.modrinth.theseus\profiles\HORIZONS 1.1.1\mods\nvidium-0.2.6-beta.jar).
	 - Cambia el mod 'Sodium' (sodium) 0.5.8+mc1.20.1 por la versión 0.5.10.
Dependencias no satisfechas:
	 - ¡El mod 'Indium' (indium) 1.0.32+mc1.20.1 necesita la versión 0.5.9 o la versión 0.5.10 de el mod 'Sodium' (sodium), pero sólo tienes una versión incorrecta: 0.5.8+mc1.20.1!
	 - ¡El mod 'Iris' (iris) 1.7.1+mc1.20.1 necesita la versión 0.5.10 de el mod 'Sodium' (sodium), pero sólo tienes una versión incorrecta: 0.5.8+mc1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
this happend when i use 0.5.8

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
Hemos encontrado una solución prometedora:
	 - Quita el mod 'Nvidium' (nvidium) 0.2.6-beta (C:\Users\rosad\AppData\Roaming\com.modrinth.theseus\profiles\HORIZONS 1.1.1\mods\nvidium-0.2.6-beta.jar).
	 - Cambia el mod 'Sodium' (sodium) 0.5.7+mc1.20.1 por la versión 0.5.10.
Dependencias no satisfechas:
	 - ¡El mod 'Indium' (indium) 1.0.32+mc1.20.1 necesita la versión 0.5.9 o la versión 0.5.10 de el mod 'Sodium' (sodium), pero sólo tienes una versión incorrecta: 0.5.7+mc1.20.1!
	 - ¡El mod 'Iris' (iris) 1.7.1+mc1.20.1 necesita la versión 0.5.10 de el mod 'Sodium' (sodium), pero sólo tienes una versión incorrecta: 0.5.7+mc1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
and this when i use 0.5.7

**Comment by sanshz** [comment]
Basically what you can do until there is any update from nvidium
- Use latest Sodium and Indium, but wait for nvidium's update
- Or download Sodium 0.5.8, Nvidium 0.2.7 and Indium 1.0.31 (and check if your other mods are compatible with these ones)

I would recommend download latest Sodium and other mods, and wait for Nvidium's compatibility with latest Sodium version

**Comment by KarmaMarazu** [comment]
If you change the version of sodium nvidium is compatible with (there is an example of how in the support channel in the discord) it will most likely just work if you follow that

**Comment by DefomCode** [comment]
why won't the developer update compatibility? it's not easy to rollback version of sodium, for this you need to rollback ALL its addons AND ALL MODS that use sodium. It will be much easier for a user (especially an ordinary one) to delete a nividium and say that it is shit, and what will they be wrong about if it is not compatible with the most popular optimization mod?

**Comment by Skywalker8510** [comment]
If you want it to be updated so badly do it yourself. These things take time to do. they don’t just happen overnight. The developer also has a life of their own and things to do.

**Comment by KarmaMarazu** [comment]
[fabric_loader_dependencies.json](https://github.com/user-attachments/files/15989977/fabric_loader_dependencies.json)
how to fix it urself just drop it in the config folder

**Comment by TheShadyyOneYT** [comment]
> [fabric_loader_dependencies.json](https://github.com/user-attachments/files/15989977/fabric_loader_dependencies.json) how to fix it urself just drop it in the config folder

how does that work? I'm not familar with JSON really, just curious if anyone here can elaborate how to update Nvidium personally from 0.5.8 sodium to 0.5.11 sodium compatiblity. Looking for Fabric 1.20.1 compat with it, how do I do that for 1.20.1 via this json?

**Comment by KarmaMarazu** [comment]
> how does that work? I'm not familar with JSON really, just curious if anyone here can elaborate how to update Nvidium personally from 0.5.8 sodium to 0.5.11 sodium compatiblity. Looking for Fabric 1.20.1 compat with it, how do I do that for 1.20.1 via this json?

Go into your .minecraft/config folder and drop this file in there this file also works for 1.20.1

**Comment by TheShadyyOneYT** [comment]
Do i type anything in the config? its blank. I put in into my config folder. it didn't seem to work, clearly I'm a dumbass and missing something that is probably obvious.

**Comment by TheShadyyOneYT** [comment]
nvm it worked thanks

**Comment by Domen-1** [comment]
Sounds silly..... but I dragged this json file into the configs but it didn't help. Version nvidium 0.2.6 and sodium 0.5.11
The incompatibility error between nvidium 0.2.6 and sodium 0.5.11 still appears.

**Comment by TheShadyyOneYT** [comment]
you literally just drag it into the configs folder, no joke it just works. can u send a video on how you did it or screenshots, a visual of how you managed it so I can better understand why it didn't work for you? because when i first tried to understand it, it made no sense. but then eventually it did

**Comment by TheShadyyOneYT** [comment]
> Sounds silly..... but I dragged this `json file` into the configs but it didn't help. Version nvidium 0.2.6 and sodium 0.5.11 The incompatibility error between nvidium 0.2.6 and sodium 0.5.11 still appears.

You need to copy it into a `notepad file`. If it’s just straight JSON it won’t work. As most mods and in game files within Minecraft house `JSON files` within `notepad files`. Granted I may be wrong about this, but that is how I got it to work. I copied the dependencies into a `notepad file` by selecting: `Open with Notepad` and it worked

**Comment by Domen-1** [comment]
I fixed it, thanks

**Comment by KarmaMarazu** [comment]
> You need to copy it into a `notepad file`. If it’s just straight JSON it won’t work. As most mods and in game files within Minecraft house `JSON files` within `notepad files`. Granted I may be wrong about this, but that is how I got it to work. I copied the dependencies into a `notepad file` by selecting: `Open with Notepad` and it worked

Weird it should just work if you put the .json file there mc doesnt use notepad. Notepad is just a way to read the file what sometimes does break it ive seen is if there is (1) or (2) etc behind it

**Comment by TheShadyyOneYT** [comment]
Granted I may be wrong. I think you are correct about reading them as JSON files via notepad. That was my main intention but you are correct. I’m not very knowledgeable with JSON files, note pads, etc. still learning 

edit: there called `text files` whoops, probably where the confusion comes from 💀

**Comment by DialingSpoon527** [comment]
Just an FYI, this no longer works with sodium 0.5.13. Because `ChunkVertexEncoder.write();` now passes a  Vertex[] instead of each  Vertex one at a time.

**Comment by lgbtaye777** [comment]
Unfortunately, this no longer works because Sodium 0.5.13 introduces a real binary/API break with Nvidium. Even with a dependency override, the game crashes at runtime, not during dependency resolution. The crash report shows an `AbstractMethodError`: a class from Nvidium (`me.cortex.nvidium.sodiumCompat.NvidiumCompactChunkVertex...`) does not implement the method `write(long, Material, ChunkVertexEncoder$Vertex[], int)` from the `ChunkVertexEncoder` interface, which was changed in Sodium 0.5.13. In other words, the override only suppresses Fabric’s version check, but Nvidium itself is compiled against an older Sodium API and is no longer binary-compatible.

Environment: Minecraft 1.20.1 (Fabric), Sodium 0.5.13.

**Comment by stranger1200** [comment]
For anyone interested I've made a fork that fixes this: 
https://github.com/stranger1200/nvidium

Had to broaden the Sodium version constraint so Fabric's dependency 
check passes, and update getEncoder() to use the new Vertex[] array 
signature. Tested with Sodium 0.5.13+mc1.20.1. Precompiled JAR is 
in the releases.
